[build.environment]
  NETLIFY_FEEDBACK_DISABLED = "true"
  NETLIFY_DRAWER_DISABLED = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
